
trigger:
- main
 
pool:
  vmImage: ubuntu-latest
 
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'
 
- script: |
    # Find the directory containing result.html
    REPORTS_DIR=$(find $(System.DefaultWorkingDirectory)/reports -name "result.html" -exec dirname {} \; | head -n 1)
    echo "##vso[task.setvariable variable=REPORTS_DIR]$REPORTS_DIR"
  displayName: 'Find Extent Report'
 
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/surefire-reports/*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)'
 
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(REPORTS_DIR)'
    artifactName: 'ExtentReports'
    publishLocation: 'Container'